apiVersion: batch/v1
kind: Job
metadata:
  name: edit-pexels-2039
spec:
  template:
    spec:
      priorityClassName: research-low
      restartPolicy: "Never"
      containers:
        - name: edit-img
          image: ghcr.io/janpf/niaa/pytorch:latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - mountPath: /workspace
              name: workspace
            - mountPath: /scratch
              name: scratch
            - mountPath: /dataset
              name: dataset
            - mountPath: /out
              name: out
            - mountPath: /dev/shm
              name: dshm
          command:
            - python
            - edit_img_pexels_2039.py
      volumes:
        - name: dataset
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/datasets/pexels/images"
            secretRef:
              name: ceph-secret
        - name: out
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/datasets/pexels_dist/images"
            secretRef:
              name: ceph-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/editing"
            secretRef:
              name: ceph-secret
        - name: workspace
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/editing"
            secretRef:
              name: ceph-secret
        - name: dshm
          emptyDir:
            medium: Memory
