apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      priorityClassName: research-med
      containers:
        - name: nicer-edit-test
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/studseizinger/nicer_env:0.0.3
          workingDir: /workdir
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - mountPath: /workdir
              name: localdir
          command:
            - python3
            - analysis/pexels_analysis.py
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: localdir
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: studseizinger  # <namespace>
            path: "/home/stud/seizinger/git/NICER" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret