apiVersion: batch/v1
kind: Job
metadata:
  name: survey-nicer-edit-job
spec:
  template:
    spec:
      priorityClassName: research-med
      containers:
        - name: survey-nicer-build
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/studseizinger/nicer_env:0.0.3
          workingDir: /workdir
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/workdir/cache/"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "48"
              memory: "10Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "16"
              memory: "10Gi"
          volumeMounts:
            - mountPath: /workdir
              name: localdir
            - mountPath: /dev/shm
              name: dshm
          command:
            - python3
            - build_survey_nicer.py
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: localdir
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: studseizinger  # <namespace>
            path: "/home/stud/seizinger/git/NICER" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
        - name: dshm
          emptyDir:
            medium: Memory