apiVersion: batch/v1
kind: Job
metadata:
  name: copy-job
spec:
  template:
    spec:
      priorityClassName: research-med
      restartPolicy: "OnFailure"
      containers:
        - name: hyperparam-test
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/studseizinger/nicer_env:0.0.3
          workingDir: /workdir
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "2"
              memory: "8Gi"
          volumeMounts:
            - mountPath: /workdir
              name: localdir
            - mountPath: /dev/shm
              name: dshm
          command:
            - python
            - copy_finished.py
      imagePullSecrets:
        - name: lsx-registry
      volumes:
        - name: localdir
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/"
            secretRef:
              name: ceph-secret
        - name: dshm
          emptyDir:
            medium: Memory
