apiVersion: batch/v1
kind: Job
metadata:
  name: edit-img
spec:
  template:
    spec:
      priorityClassName: research-med
      restartPolicy: "Never"
      containers:
        - name: hyperparam_test
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/studseizinger/nicer_env:0.0.3
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "48"
              memory: "10Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "48"
              memory: "10Gi"
          volumeMounts:
            - mountPath: /workspace
              name: workspace
            - mountPath: /dataset_orig
              name: dataset_orig
            - mountPath: /dataset_dist
              name: dataset_dist
            - mountPath: /out
              name: out
            - mountPath: /dev/shm
              name: dshm
          command:
            - python
            - hyperparamtest.py
            - --sample_size
            - 100
            - --optim_lr
            - 0.025
            - --gamma
            - 0.1
            - --score_pow
            - 1.5
            - --composite_balance
            - 0
            - --adaptive_score_offset
            - 0.3
      volumes:
        - name: dataset_orig
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/datasets/pexels/images"
            secretRef:
              name: ceph-secret
        - name: dataset_dist
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/datasets/pexels_dist/images"
            secretRef:
              name: ceph-secret
        - name: out
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/out"
            secretRef:
              name: ceph-secret
        - name: workspace
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/"
            secretRef:
              name: ceph-secret
        - name: dshm
          emptyDir:
            medium: Memory
