apiVersion: batch/v1
kind: Job
metadata:
  name: edit-img
spec:
  template:
    spec:
      priorityClassName: research-med
      restartPolicy: "Never"
      containers:
        - name: edit-img
          image: ghcr.io/janpf/niaa/pytorch:latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: ".1"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /scratch
              name: scratch
            - mountPath: /dataset
              name: dataset
            - mountPath: /out
              name: out
            - mountPath: /dev/shm
              name: dshm
          command:
            - python
            - edit_img.py
            - --infile
            - /dataset/pexels-photo-1565772.jpeg
            - --outfile
            - /out/test.jpeg
            - -d=brightness,-3
            - -d=brightness,3
            - -d=contrast,-3
            - -d=contrast,3
            - -d=saturation,-3
            - -d=saturation,3
            - -d=exposure,-3
            - -d=exposure,3
            - -d=shadows,-3
            - -d=shadows,3
            - -d=highlights,-3
            - -d=highlights,3
      volumes:
        - name: dataset
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/datasets/pexels/images"
            secretRef:
              name: ceph-secret
        - name: out
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/datasets/pexels_dist/images"
            secretRef:
              name: ceph-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studseizinger
            path: "/home/stud/seizinger/git/NICER/editing"
            secretRef:
              name: ceph-secret
        - name: dshm
          emptyDir:
            medium: Memory
